# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:categories/:title.html
gems: [jekyll-paginate-v2]
port: 3000
safe: true
plugins_dir:
  - jekyll-paginate-v2


# edit here to achieve your personal greatness
url: https://www.ppolivka.com/
baseurl: /
title: Pavel Polívka
author: Pavel Polívka
description: Personal blog and resume
avatar: profile.png
email: polivka.pavel@gmail.com
github: PavlikPolivka # username
facebook: pavel.polivka
linkedin: pavel-polívka-863a1356
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-64345822-1


# needed for travis-ci build
exclude: [vendor]

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  offset: 2
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
