---
label: Project
hide_body: false
is_partial: false
fields:
- type: text
  label: layout
  name: layout
  hidden: false
  config:
    required: true
  default: post
- type: text
  name: categories
  label: categories
  hidden: false
  config:
    required: true
  default: project
- type: text
  name: title
  label: title
